from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .frontend import parse_packet_parser_subset
from .ir import PacketAssign, PacketBoundsCheck, PacketProgram, PacketTotalCheck


DEFAULT_PACKET_SPEC = {
    "sizes": {
        "ethhdr": {"const": "ETH_SZ", "bytes": 14},
        "iphdr": {"const": "IP_SZ", "bytes": 20},
        "tcphdr": {"const": "TCP_SZ", "bytes": 20},
        "tcp_timestamp_opt": {"const": "TS_SZ", "bytes": 12}
    },
    "observables": ["eth", "iph", "tcph", "ts_opt"]
}


def generate_packet_z3(orig_path: str | Path, opt_path: str | Path, spec_path: str | Path | None = None) -> str:
    spec = _load_spec(spec_path)
    orig = parse_packet_parser_subset(orig_path, "original")
    opt = parse_packet_parser_subset(opt_path, "optimized")

    lines = [
        "from z3 import *",
        "",
        "# Generated by eBPF_to_z3.translator.translate",
        "",
        "# Symbolic packet memory",
        "mem = Array('mem', BitVecSort(64), BitVecSort(8))",
        "",
        "# Symbolic pointers",
        "data = BitVec('data', 64)",
        "data_end = BitVec('data_end', 64)",
        "",
        "# Header sizes",
    ]
    for struct_name, size_info in spec["sizes"].items():
        lines.append(f"{size_info['const']} = BitVecVal({size_info['bytes']}, 64)  # struct {struct_name}")
    lines.append("")

    orig_emitter = PacketEmitter(orig, "orig", spec)
    opt_emitter = PacketEmitter(opt, "opt", spec)
    lines.extend(["# Original parser"])
    lines.extend(orig_emitter.emit())
    lines.extend(["# Optimized parser"])
    lines.extend(opt_emitter.emit())

    mismatch_terms = [f"{orig_emitter.cond_name} != {opt_emitter.cond_name}"]
    for name in spec.get("observables", []):
        if name in orig_emitter.vars and name in opt_emitter.vars:
            mismatch_terms.append(f"And({orig_emitter.cond_name}, {orig_emitter.var(name)} != {opt_emitter.var(name)})")

    lines.extend(
        [
            "# Equivalence proof",
            "s = Solver()",
            "s.add(data == BitVecVal(0, 64))",
            f"s.add(Or({', '.join(mismatch_terms)}))",
            "",
            "result = s.check()",
            "print(result)",
            "if result == sat:",
            '    print("Counterexample:")',
            "    print(s.model())",
            "else:",
            '    print("Equivalent")',
            "",
        ]
    )
    return "\n".join(lines)


class PacketEmitter:
    def __init__(self, program: PacketProgram, suffix: str, spec: dict[str, Any]):
        self.program = program
        self.suffix = suffix
        self.spec = spec
        self.cond_name = f"{suffix}_cond"
        self.vars: set[str] = set()
        self.lines: list[str] = []

    def emit(self) -> list[str]:
        self.lines.append(f"{self.cond_name} = BoolVal(True)")
        for stmt in self.program.statements:
            if isinstance(stmt, PacketAssign):
                self._emit_assign(stmt)
            elif isinstance(stmt, PacketBoundsCheck):
                self._emit_bounds_check(stmt)
            elif isinstance(stmt, PacketTotalCheck):
                self._emit_total_check(stmt)
            else:
                raise ValueError(f"unsupported packet statement {stmt}")
        self.lines.append("")
        return self.lines

    def var(self, name: str) -> str:
        return f"{name}_{self.suffix}"

    def _emit_assign(self, stmt: PacketAssign) -> None:
        target = self.var(stmt.name)
        expr = "data" if stmt.base == "data" else self.var(stmt.base)
        if stmt.offset_struct:
            expr = f"{expr} + {self._size_const(stmt.offset_struct)}"

        if self.suffix == "orig" and self.vars:
            expr = f"If({self.cond_name}, {expr}, BitVecVal(0, 64))"
        elif self.suffix == "opt":
            expr = f"If({self.cond_name}, {expr}, BitVecVal(0, 64))"

        self.lines.append(f"{target} = {expr}")
        self.vars.add(stmt.name)

    def _emit_bounds_check(self, stmt: PacketBoundsCheck) -> None:
        ptr = self.var(stmt.ptr)
        self.lines.append(f"{self.cond_name} = And({self.cond_name}, {ptr} + {self._size_const(stmt.ptr_struct)} <= data_end)")

    def _emit_total_check(self, stmt: PacketTotalCheck) -> None:
        total_terms = " + ".join(self._size_const(struct_name) for struct_name in stmt.structs)
        self.lines.append(f"TOTAL_{self.suffix.upper()} = {total_terms}")
        self.lines.append(f"{self.cond_name} = data + TOTAL_{self.suffix.upper()} <= data_end")

    def _size_const(self, struct_name: str) -> str:
        try:
            return self.spec["sizes"][struct_name]["const"]
        except KeyError as exc:
            raise ValueError(f"missing size spec for struct {struct_name}") from exc


def _load_spec(spec_path: str | Path | None) -> dict[str, Any]:
    if spec_path is None:
        return DEFAULT_PACKET_SPEC
    spec = DEFAULT_PACKET_SPEC.copy()
    user_spec = json.loads(Path(spec_path).read_text())
    spec["sizes"] = {**spec["sizes"], **user_spec.get("sizes", {})}
    spec["observables"] = user_spec.get("observables", spec["observables"])
    return spec
