from z3 import *

# Generated by eBPF_to_z3.translator.translate

# Declarations
Val = Datatype('Val')
Val.declare('mkVal', ('flag', BitVecSort(32)), ('counter', BitVecSort(64)))
Val = Val.create()

ctl_array_0_flag = Array('ctl_array_0_flag', BitVecSort(32), BitVecSort(1))
ctl_array_0 = Array('ctl_array_0', BitVecSort(32), BitVecSort(32))

cntrs_array_0_flag = Array('cntrs_array_0_flag', BitVecSort(32), BitVecSort(1))
cntrs_array_0 = Array('cntrs_array_0', BitVecSort(32), BitVecSort(64))

merged_map_0_flag = Array('merged_map_0_flag', BitVecSort(32), BitVecSort(1))
merged_map_0 = Array('merged_map_0', BitVecSort(32), Val)

# Relational Assumptions
preconditions = [
    (Select(ctl_array_0_flag, BitVecVal(0, 32)) & Select(cntrs_array_0_flag, BitVecVal(0, 32))) == Select(merged_map_0_flag, BitVecVal(0, 32)),
    Select(ctl_array_0, BitVecVal(0, 32)) == Val.flag(Select(merged_map_0, BitVecVal(0, 32))),
    Select(cntrs_array_0, BitVecVal(0, 32)) == Val.counter(Select(merged_map_0, BitVecVal(0, 32))),
]

# Original Program Semantics
# original program: original
cntrs_array_0_1 = If(
    And(Not(Or(Select(ctl_array_0_flag, BitVecVal(0, 32)) == BitVecVal(0, 1), Select(ctl_array_0, BitVecVal(0, 32)) == BitVecVal(0, 32))), Select(cntrs_array_0_flag, BitVecVal(0, 32)) != BitVecVal(0, 1)),
    Store(cntrs_array_0, BitVecVal(0, 32), Select(cntrs_array_0, BitVecVal(0, 32)) + BitVecVal(1, 64)),
    cntrs_array_0
)

# Optimized Program Semantics
# optimized program: optimized
merged_map_0_1 = If(
    And(Not(Select(merged_map_0_flag, BitVecVal(0, 32)) == BitVecVal(0, 1)), Not(Val.flag(Select(merged_map_0, BitVecVal(0, 32))) == BitVecVal(0, 32))),
    Store(merged_map_0, BitVecVal(0, 32), Val.mkVal(Val.flag(Select(merged_map_0, BitVecVal(0, 32))), Val.counter(Select(merged_map_0, BitVecVal(0, 32))) + BitVecVal(1, 64))),
    merged_map_0
)

# Equivalence Check
s = Solver()
s.add(preconditions)
s.add(Select(cntrs_array_0_1, BitVecVal(0, 32)) != Val.counter(Select(merged_map_0_1, BitVecVal(0, 32))))

result = s.check()
print("Verification result:", result)
if result == sat:
    print("\nCounterexample found:\n")
    print(s.model())
else:
    print("\nPrograms are equivalent.")
