from z3 import *

# Generated by eBPF_to_z3.translator.translate

# Symbolic packet memory
mem = Array('mem', BitVecSort(64), BitVecSort(8))

# Symbolic pointers
data = BitVec('data', 64)
data_end = BitVec('data_end', 64)

# Header sizes
ETH_SZ = BitVecVal(14, 64)  # struct ethhdr
IP_SZ = BitVecVal(20, 64)  # struct iphdr
TCP_SZ = BitVecVal(20, 64)  # struct tcphdr
TS_SZ = BitVecVal(12, 64)  # struct tcp_timestamp_opt

# Original parser
orig_cond = BoolVal(True)

# Optimized parser
opt_cond = BoolVal(True)

# Equivalence proof
s = Solver()
s.add(data == BitVecVal(0, 64))
s.add(Or(orig_cond != opt_cond))

result = s.check()
print(result)
if result == sat:
    print("Counterexample:")
    print(s.model())
else:
    print("Equivalent")
